package com.pineapple.app.theme

import androidx.compose.ui.graphics.Color


val light_primary = Color(0xFF0c6d35)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFF9ef6af)
val light_onPrimaryContainer = Color(0xFF002109)
val light_secondary = Color(0xFF516352)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd3e8d2)
val light_onSecondaryContainer = Color(0xFF0d1f11)
val light_tertiary = Color(0xFF3a656e)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFbdeaf4)
val light_onTertiaryContainer = Color(0xFF001f25)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfbfdf7)
val light_onBackground = Color(0xFF1a1c19)
val light_surface = Color(0xFFF7FCF0)
val light_onSurface = Color(0xFF1a1c19)
val light_surfaceVariant = Color(0xFFdde5da)
val light_onSurfaceVariant = Color(0xFF414941)
val light_outline = Color(0xFF717970)
val light_inverseOnSurface = Color(0xFFf0f2ec)
val light_inverseSurface = Color(0xFF2f312e)
val light_inversePrimary = Color(0xFF83d995)

val dark_primary = Color(0xFF83d995)
val dark_onPrimary = Color(0xFF003916)
val dark_primaryContainer = Color(0xFF005323)
val dark_onPrimaryContainer = Color(0xFF9ef6af)
val dark_secondary = Color(0xFFb7ccb7)
val dark_onSecondary = Color(0xFF233425)
val dark_secondaryContainer = Color(0xFF394b3b)
val dark_onSecondaryContainer = Color(0xFFd3e8d2)
val dark_tertiary = Color(0xFFa2ced8)
val dark_onTertiary = Color(0xFF01363e)
val dark_tertiaryContainer = Color(0xFF204d56)
val dark_onTertiaryContainer = Color(0xFFbdeaf4)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1a1c19)
val dark_onBackground = Color(0xFFe2e3de)
val dark_surface = Color(0xFF1a1c19)
val dark_onSurface = Color(0xFFe2e3de)
val dark_surfaceVariant = Color(0xFF414941)
val dark_onSurfaceVariant = Color(0xFFc1c8be)
val dark_outline = Color(0xFF8b9389)
val dark_inverseOnSurface = Color(0xFF1a1c19)
val dark_inverseSurface = Color(0xFFe2e3de)
val dark_inversePrimary = Color(0xFF0c6d35)